###
# POST http://localhost:6070/api/auth/login

POST http://localhost:6070/api/auth/login

Content-Type: application/json
{
  "username": "yultrish",
  "email": "yultrish@gmail.com"
}

###

POST http://localhost:6070/api/auth/signup

Content-Type: application/json
{
  "username": "yultris",
  "email": "yultris@gmail.com",
  "password": "yul123"
  
}

###
GET http://localhost:6070/api/auth/v1/getMeals
